// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/mesh-projects/api/discovery/v1alpha1/registry.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/solo-io/mesh-projects/pkg/api/core.zephyr.solo.io/v1alpha1/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//The MeshService is an abstraction for a service which we have discovered to be, or are told, is part of a
//given mesh. The Mesh object has references to the MeshServices which belong to it.
type MeshServiceSpec struct {
	KubeService *KubeService `protobuf:"bytes,1,opt,name=kube_service,json=kubeService,proto3" json:"kube_service,omitempty"`
	// The mesh with which this service is associated
	Mesh                 *types.ResourceRef                 `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	Subsets              map[string]*MeshServiceSpec_Subset `protobuf:"bytes,3,rep,name=subsets,proto3" json:"subsets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Federation           *Federation                        `protobuf:"bytes,4,opt,name=federation,proto3" json:"federation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *MeshServiceSpec) Reset()         { *m = MeshServiceSpec{} }
func (m *MeshServiceSpec) String() string { return proto.CompactTextString(m) }
func (*MeshServiceSpec) ProtoMessage()    {}
func (*MeshServiceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{0}
}
func (m *MeshServiceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServiceSpec.Unmarshal(m, b)
}
func (m *MeshServiceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServiceSpec.Marshal(b, m, deterministic)
}
func (m *MeshServiceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServiceSpec.Merge(m, src)
}
func (m *MeshServiceSpec) XXX_Size() int {
	return xxx_messageInfo_MeshServiceSpec.Size(m)
}
func (m *MeshServiceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServiceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServiceSpec proto.InternalMessageInfo

func (m *MeshServiceSpec) GetKubeService() *KubeService {
	if m != nil {
		return m.KubeService
	}
	return nil
}

func (m *MeshServiceSpec) GetMesh() *types.ResourceRef {
	if m != nil {
		return m.Mesh
	}
	return nil
}

func (m *MeshServiceSpec) GetSubsets() map[string]*MeshServiceSpec_Subset {
	if m != nil {
		return m.Subsets
	}
	return nil
}

func (m *MeshServiceSpec) GetFederation() *Federation {
	if m != nil {
		return m.Federation
	}
	return nil
}

type MeshServiceSpec_Subset struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshServiceSpec_Subset) Reset()         { *m = MeshServiceSpec_Subset{} }
func (m *MeshServiceSpec_Subset) String() string { return proto.CompactTextString(m) }
func (*MeshServiceSpec_Subset) ProtoMessage()    {}
func (*MeshServiceSpec_Subset) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{0, 0}
}
func (m *MeshServiceSpec_Subset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServiceSpec_Subset.Unmarshal(m, b)
}
func (m *MeshServiceSpec_Subset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServiceSpec_Subset.Marshal(b, m, deterministic)
}
func (m *MeshServiceSpec_Subset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServiceSpec_Subset.Merge(m, src)
}
func (m *MeshServiceSpec_Subset) XXX_Size() int {
	return xxx_messageInfo_MeshServiceSpec_Subset.Size(m)
}
func (m *MeshServiceSpec_Subset) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServiceSpec_Subset.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServiceSpec_Subset proto.InternalMessageInfo

func (m *MeshServiceSpec_Subset) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Federation struct {
	MulticlusterDnsName  string               `protobuf:"bytes,1,opt,name=multicluster_dns_name,json=multiclusterDnsName,proto3" json:"multicluster_dns_name,omitempty"`
	FederatedToWorkloads []*types.ResourceRef `protobuf:"bytes,2,rep,name=federated_to_workloads,json=federatedToWorkloads,proto3" json:"federated_to_workloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Federation) Reset()         { *m = Federation{} }
func (m *Federation) String() string { return proto.CompactTextString(m) }
func (*Federation) ProtoMessage()    {}
func (*Federation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{1}
}
func (m *Federation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Federation.Unmarshal(m, b)
}
func (m *Federation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Federation.Marshal(b, m, deterministic)
}
func (m *Federation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Federation.Merge(m, src)
}
func (m *Federation) XXX_Size() int {
	return xxx_messageInfo_Federation.Size(m)
}
func (m *Federation) XXX_DiscardUnknown() {
	xxx_messageInfo_Federation.DiscardUnknown(m)
}

var xxx_messageInfo_Federation proto.InternalMessageInfo

func (m *Federation) GetMulticlusterDnsName() string {
	if m != nil {
		return m.MulticlusterDnsName
	}
	return ""
}

func (m *Federation) GetFederatedToWorkloads() []*types.ResourceRef {
	if m != nil {
		return m.FederatedToWorkloads
	}
	return nil
}

type KubeService struct {
	Ref                  *types.ResourceRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	SelectorLabels       map[string]string  `protobuf:"bytes,2,rep,name=selector_labels,json=selectorLabels,proto3" json:"selector_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KubeService) Reset()         { *m = KubeService{} }
func (m *KubeService) String() string { return proto.CompactTextString(m) }
func (*KubeService) ProtoMessage()    {}
func (*KubeService) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{2}
}
func (m *KubeService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubeService.Unmarshal(m, b)
}
func (m *KubeService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubeService.Marshal(b, m, deterministic)
}
func (m *KubeService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeService.Merge(m, src)
}
func (m *KubeService) XXX_Size() int {
	return xxx_messageInfo_KubeService.Size(m)
}
func (m *KubeService) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeService.DiscardUnknown(m)
}

var xxx_messageInfo_KubeService proto.InternalMessageInfo

func (m *KubeService) GetRef() *types.ResourceRef {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *KubeService) GetSelectorLabels() map[string]string {
	if m != nil {
		return m.SelectorLabels
	}
	return nil
}

type MeshServiceStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshServiceStatus) Reset()         { *m = MeshServiceStatus{} }
func (m *MeshServiceStatus) String() string { return proto.CompactTextString(m) }
func (*MeshServiceStatus) ProtoMessage()    {}
func (*MeshServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{3}
}
func (m *MeshServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshServiceStatus.Unmarshal(m, b)
}
func (m *MeshServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshServiceStatus.Marshal(b, m, deterministic)
}
func (m *MeshServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshServiceStatus.Merge(m, src)
}
func (m *MeshServiceStatus) XXX_Size() int {
	return xxx_messageInfo_MeshServiceStatus.Size(m)
}
func (m *MeshServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MeshServiceStatus proto.InternalMessageInfo

//
//The MeshWorkload is an abstraction for a workload/client which we have discovered to be, or are told, is part of a
//given mesh. The Mesh object has references to the MeshWorkloads which belong to it.
type MeshWorkloadSpec struct {
	//
	//Resource ref to the underlying kubernetes controller which is managing the pods associated with the workloads.
	//It has the generic name kube_controller as it can represent either a deployment or a daemonset. Or potentially
	//any other kubernetes object which creates injected pods.
	//
	//The type is specified on the ResourceRef.APIGroup and ResourceRef.Kind fields
	KubeControllerRef *types.ResourceRef `protobuf:"bytes,1,opt,name=kube_controller_ref,json=kubeControllerRef,proto3" json:"kube_controller_ref,omitempty"`
	KubePod           *KubePod           `protobuf:"bytes,3,opt,name=kube_pod,json=kubePod,proto3" json:"kube_pod,omitempty"`
	// The mesh with which this workload is associated
	Mesh                 *types.ResourceRef `protobuf:"bytes,2,opt,name=mesh,proto3" json:"mesh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MeshWorkloadSpec) Reset()         { *m = MeshWorkloadSpec{} }
func (m *MeshWorkloadSpec) String() string { return proto.CompactTextString(m) }
func (*MeshWorkloadSpec) ProtoMessage()    {}
func (*MeshWorkloadSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{4}
}
func (m *MeshWorkloadSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshWorkloadSpec.Unmarshal(m, b)
}
func (m *MeshWorkloadSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshWorkloadSpec.Marshal(b, m, deterministic)
}
func (m *MeshWorkloadSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshWorkloadSpec.Merge(m, src)
}
func (m *MeshWorkloadSpec) XXX_Size() int {
	return xxx_messageInfo_MeshWorkloadSpec.Size(m)
}
func (m *MeshWorkloadSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshWorkloadSpec.DiscardUnknown(m)
}

var xxx_messageInfo_MeshWorkloadSpec proto.InternalMessageInfo

func (m *MeshWorkloadSpec) GetKubeControllerRef() *types.ResourceRef {
	if m != nil {
		return m.KubeControllerRef
	}
	return nil
}

func (m *MeshWorkloadSpec) GetKubePod() *KubePod {
	if m != nil {
		return m.KubePod
	}
	return nil
}

func (m *MeshWorkloadSpec) GetMesh() *types.ResourceRef {
	if m != nil {
		return m.Mesh
	}
	return nil
}

type KubePod struct {
	// these are the labels directly from the pods that this controller owns
	// NB: these are NEITHER the matchLabels nor the labels on the controller itself.
	// we need these to determine which services are backed by this workload, and
	// the service backing is determined by the pod labels
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceAccountName   string            `protobuf:"bytes,4,opt,name=service_account_name,json=serviceAccountName,proto3" json:"service_account_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KubePod) Reset()         { *m = KubePod{} }
func (m *KubePod) String() string { return proto.CompactTextString(m) }
func (*KubePod) ProtoMessage()    {}
func (*KubePod) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{5}
}
func (m *KubePod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubePod.Unmarshal(m, b)
}
func (m *KubePod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubePod.Marshal(b, m, deterministic)
}
func (m *KubePod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubePod.Merge(m, src)
}
func (m *KubePod) XXX_Size() int {
	return xxx_messageInfo_KubePod.Size(m)
}
func (m *KubePod) XXX_DiscardUnknown() {
	xxx_messageInfo_KubePod.DiscardUnknown(m)
}

var xxx_messageInfo_KubePod proto.InternalMessageInfo

func (m *KubePod) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *KubePod) GetServiceAccountName() string {
	if m != nil {
		return m.ServiceAccountName
	}
	return ""
}

type MeshWorkloadStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshWorkloadStatus) Reset()         { *m = MeshWorkloadStatus{} }
func (m *MeshWorkloadStatus) String() string { return proto.CompactTextString(m) }
func (*MeshWorkloadStatus) ProtoMessage()    {}
func (*MeshWorkloadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac550e3ffa031dc0, []int{6}
}
func (m *MeshWorkloadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshWorkloadStatus.Unmarshal(m, b)
}
func (m *MeshWorkloadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshWorkloadStatus.Marshal(b, m, deterministic)
}
func (m *MeshWorkloadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshWorkloadStatus.Merge(m, src)
}
func (m *MeshWorkloadStatus) XXX_Size() int {
	return xxx_messageInfo_MeshWorkloadStatus.Size(m)
}
func (m *MeshWorkloadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshWorkloadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MeshWorkloadStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MeshServiceSpec)(nil), "discovery.zephyr.solo.io.MeshServiceSpec")
	proto.RegisterMapType((map[string]*MeshServiceSpec_Subset)(nil), "discovery.zephyr.solo.io.MeshServiceSpec.SubsetsEntry")
	proto.RegisterType((*MeshServiceSpec_Subset)(nil), "discovery.zephyr.solo.io.MeshServiceSpec.Subset")
	proto.RegisterType((*Federation)(nil), "discovery.zephyr.solo.io.Federation")
	proto.RegisterType((*KubeService)(nil), "discovery.zephyr.solo.io.KubeService")
	proto.RegisterMapType((map[string]string)(nil), "discovery.zephyr.solo.io.KubeService.SelectorLabelsEntry")
	proto.RegisterType((*MeshServiceStatus)(nil), "discovery.zephyr.solo.io.MeshServiceStatus")
	proto.RegisterType((*MeshWorkloadSpec)(nil), "discovery.zephyr.solo.io.MeshWorkloadSpec")
	proto.RegisterType((*KubePod)(nil), "discovery.zephyr.solo.io.KubePod")
	proto.RegisterMapType((map[string]string)(nil), "discovery.zephyr.solo.io.KubePod.LabelsEntry")
	proto.RegisterType((*MeshWorkloadStatus)(nil), "discovery.zephyr.solo.io.MeshWorkloadStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/mesh-projects/api/discovery/v1alpha1/registry.proto", fileDescriptor_ac550e3ffa031dc0)
}

var fileDescriptor_ac550e3ffa031dc0 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0xeb, 0x7e, 0xe9, 0xd7, 0x9b, 0x8a, 0xb6, 0x93, 0x50, 0x59, 0x59, 0xa0, 0x10, 0x81,
	0x54, 0x16, 0xb5, 0xdb, 0x80, 0x10, 0x45, 0x6c, 0x0a, 0x6d, 0x85, 0xc4, 0x8f, 0x22, 0x07, 0x15,
	0x89, 0x8d, 0xe5, 0x9f, 0x9b, 0xc4, 0xc4, 0xf1, 0xb5, 0x66, 0xc6, 0x41, 0xe6, 0x49, 0x78, 0x04,
	0x5e, 0x81, 0x05, 0xef, 0xc1, 0x9a, 0x15, 0x8f, 0x81, 0x3c, 0x76, 0x52, 0xb7, 0x34, 0x84, 0x76,
	0x37, 0x3f, 0xf7, 0x9c, 0x39, 0x73, 0xcf, 0xbd, 0x17, 0x4e, 0x87, 0xa1, 0x1c, 0xa5, 0x9e, 0xe9,
	0xd3, 0xc4, 0x12, 0x14, 0xd1, 0x5e, 0x48, 0xd6, 0x04, 0xc5, 0x68, 0x2f, 0xe1, 0xf4, 0x11, 0x7d,
	0x29, 0x2c, 0x37, 0x09, 0xad, 0x20, 0x14, 0x3e, 0x4d, 0x91, 0x67, 0xd6, 0xf4, 0xc0, 0x8d, 0x92,
	0x91, 0x7b, 0x60, 0x71, 0x1c, 0x86, 0x42, 0xf2, 0xcc, 0x4c, 0x38, 0x49, 0x62, 0xc6, 0x3c, 0xc4,
	0xfc, 0x8c, 0xc9, 0x28, 0xe3, 0x66, 0xce, 0x66, 0x86, 0xd4, 0x7a, 0xf0, 0x27, 0x9d, 0x4f, 0x1c,
	0xab, 0x4c, 0x83, 0x82, 0xa4, 0xd5, 0x1c, 0xd2, 0x90, 0xd4, 0xd2, 0xca, 0x57, 0xc5, 0x69, 0xe7,
	0x9b, 0x0e, 0x9b, 0x6f, 0x50, 0x8c, 0xfa, 0xc8, 0xa7, 0xa1, 0x8f, 0xfd, 0x04, 0x7d, 0xf6, 0x12,
	0x36, 0xc6, 0xa9, 0x87, 0x8e, 0x28, 0xce, 0x0c, 0xad, 0xad, 0xed, 0xd6, 0xbb, 0xf7, 0xcd, 0x45,
	0x2a, 0xcc, 0x57, 0xa9, 0x87, 0x25, 0x81, 0x5d, 0x1f, 0x9f, 0x6f, 0xd8, 0x23, 0x58, 0xcd, 0x05,
	0x1a, 0x2b, 0x8a, 0xa1, 0x6d, 0xe6, 0xda, 0x2e, 0x83, 0x6d, 0x14, 0x94, 0x72, 0x1f, 0x6d, 0x1c,
	0xd8, 0x2a, 0x9a, 0xf5, 0x60, 0x4d, 0xa4, 0x9e, 0x40, 0x29, 0x0c, 0xbd, 0xad, 0xef, 0xd6, 0xbb,
	0x8f, 0x17, 0x3f, 0x7d, 0x49, 0xbb, 0xd9, 0x2f, 0x80, 0x27, 0xb1, 0xe4, 0x99, 0x3d, 0xa3, 0x61,
	0xc7, 0x00, 0x03, 0x0c, 0x90, 0xbb, 0x32, 0xa4, 0xd8, 0x58, 0x55, 0x6a, 0xee, 0x2d, 0x26, 0x3d,
	0x9d, 0xc7, 0xda, 0x15, 0x5c, 0xab, 0x0d, 0xb5, 0x82, 0x9e, 0xed, 0x40, 0x6d, 0xea, 0x46, 0x29,
	0x0a, 0x43, 0x6b, 0xeb, 0xbb, 0xeb, 0x76, 0xb9, 0x6b, 0x45, 0xb0, 0x51, 0x15, 0xc0, 0xb6, 0x40,
	0x1f, 0x63, 0xa6, 0x12, 0xb8, 0x6e, 0xe7, 0x4b, 0x76, 0x0a, 0xff, 0xa9, 0xd8, 0x32, 0x25, 0xfb,
	0xd7, 0xfd, 0x99, 0x5d, 0xc0, 0x9f, 0xae, 0x3c, 0xd1, 0x3a, 0x5f, 0x34, 0x80, 0x73, 0xa9, 0xac,
	0x0b, 0xb7, 0x27, 0x69, 0x24, 0x43, 0x3f, 0x4a, 0x85, 0x44, 0xee, 0x04, 0xb1, 0x70, 0x62, 0x77,
	0x82, 0xe5, 0xf3, 0x8d, 0xea, 0xe5, 0x71, 0x2c, 0xde, 0xba, 0x13, 0x64, 0x67, 0xb0, 0x53, 0x7e,
	0x10, 0x03, 0x47, 0x92, 0xf3, 0x89, 0xf8, 0x38, 0x22, 0x37, 0x10, 0xc6, 0x8a, 0xca, 0xfc, 0x72,
	0xcb, 0x9a, 0x73, 0xfc, 0x3b, 0x7a, 0x3f, 0x43, 0x77, 0x7e, 0x69, 0x50, 0xaf, 0x54, 0x05, 0xeb,
	0x82, 0xce, 0x71, 0x50, 0x56, 0xd2, 0x72, 0xd2, 0x3c, 0x98, 0x79, 0xb0, 0x29, 0x30, 0x42, 0x5f,
	0x12, 0x77, 0x22, 0xd7, 0xc3, 0x68, 0x26, 0xea, 0xf0, 0x9f, 0x2a, 0xd1, 0xec, 0x97, 0xe0, 0xd7,
	0x0a, 0x5b, 0x54, 0xc4, 0x2d, 0x71, 0xe1, 0xb0, 0x75, 0x04, 0x8d, 0x2b, 0xc2, 0xae, 0xf0, 0xad,
	0x59, 0xf5, 0x6d, 0xbd, 0xea, 0x42, 0x03, 0xb6, 0xab, 0x56, 0x49, 0x57, 0xa6, 0xa2, 0xf3, 0x43,
	0x83, 0xad, 0xfc, 0x74, 0x96, 0x11, 0xd5, 0x57, 0x3d, 0x68, 0xa8, 0xbe, 0xf2, 0x29, 0x96, 0x9c,
	0xa2, 0x08, 0xb9, 0x73, 0x9d, 0xa4, 0x6c, 0xe7, 0xe0, 0x17, 0x73, 0xac, 0x8d, 0x03, 0xf6, 0x0c,
	0xfe, 0x57, 0x8c, 0x09, 0x05, 0x86, 0xae, 0x68, 0xee, 0xfe, 0x3d, 0x37, 0x3d, 0x0a, 0xec, 0xb5,
	0x71, 0xb1, 0xb8, 0x59, 0x77, 0x76, 0xbe, 0x6b, 0xb0, 0x56, 0x52, 0xb1, 0x13, 0xa8, 0x95, 0xce,
	0x14, 0x8d, 0xba, 0xb7, 0xf4, 0x75, 0xb3, 0xea, 0x46, 0x09, 0x66, 0xfb, 0xd0, 0x2c, 0x67, 0x8d,
	0xe3, 0xfa, 0x3e, 0xa5, 0xb1, 0x2c, 0x0a, 0x77, 0x55, 0xe5, 0x9a, 0x95, 0x77, 0x47, 0xc5, 0x55,
	0x5e, 0xb7, 0xad, 0x43, 0xa8, 0xdf, 0xd4, 0xaf, 0x26, 0xb0, 0x0b, 0xce, 0x28, 0xc3, 0x9e, 0x9f,
	0x7d, 0xfd, 0x79, 0x47, 0xfb, 0xd0, 0x5b, 0x3a, 0xb0, 0x93, 0xf1, 0xf0, 0xe2, 0xd0, 0xbe, 0xf4,
	0xcf, 0xf3, 0xc9, 0x2b, 0xb3, 0x04, 0x85, 0x57, 0x53, 0x63, 0xf6, 0xe1, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd0, 0x03, 0x42, 0x7e, 0x0b, 0x06, 0x00, 0x00,
}

func (this *MeshServiceSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshServiceSpec)
	if !ok {
		that2, ok := that.(MeshServiceSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.KubeService.Equal(that1.KubeService) {
		return false
	}
	if !this.Mesh.Equal(that1.Mesh) {
		return false
	}
	if len(this.Subsets) != len(that1.Subsets) {
		return false
	}
	for i := range this.Subsets {
		if !this.Subsets[i].Equal(that1.Subsets[i]) {
			return false
		}
	}
	if !this.Federation.Equal(that1.Federation) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshServiceSpec_Subset) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshServiceSpec_Subset)
	if !ok {
		that2, ok := that.(MeshServiceSpec_Subset)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Federation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Federation)
	if !ok {
		that2, ok := that.(Federation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MulticlusterDnsName != that1.MulticlusterDnsName {
		return false
	}
	if len(this.FederatedToWorkloads) != len(that1.FederatedToWorkloads) {
		return false
	}
	for i := range this.FederatedToWorkloads {
		if !this.FederatedToWorkloads[i].Equal(that1.FederatedToWorkloads[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *KubeService) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubeService)
	if !ok {
		that2, ok := that.(KubeService)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Ref.Equal(that1.Ref) {
		return false
	}
	if len(this.SelectorLabels) != len(that1.SelectorLabels) {
		return false
	}
	for i := range this.SelectorLabels {
		if this.SelectorLabels[i] != that1.SelectorLabels[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshServiceStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshServiceStatus)
	if !ok {
		that2, ok := that.(MeshServiceStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshWorkloadSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshWorkloadSpec)
	if !ok {
		that2, ok := that.(MeshWorkloadSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.KubeControllerRef.Equal(that1.KubeControllerRef) {
		return false
	}
	if !this.KubePod.Equal(that1.KubePod) {
		return false
	}
	if !this.Mesh.Equal(that1.Mesh) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *KubePod) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KubePod)
	if !ok {
		that2, ok := that.(KubePod)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if this.Labels[i] != that1.Labels[i] {
			return false
		}
	}
	if this.ServiceAccountName != that1.ServiceAccountName {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshWorkloadStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshWorkloadStatus)
	if !ok {
		that2, ok := that.(MeshWorkloadStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
