// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/service-mesh-hub/api/settings/v1alpha2/settings.proto

package v1alpha2

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1alpha2 "github.com/solo-io/service-mesh-hub/pkg/api/networking.smh.solo.io/v1alpha2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Configure global settings and defaults.
type SettingsSpec struct {
	// Configure default mTLS settings for TrafficTargets (MTLS declared in TrafficPolicies take precedence)
	Mtls                 *v1alpha2.TrafficPolicySpec_MTLS `protobuf:"bytes,1,opt,name=mtls,proto3" json:"mtls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SettingsSpec) Reset()         { *m = SettingsSpec{} }
func (m *SettingsSpec) String() string { return proto.CompactTextString(m) }
func (*SettingsSpec) ProtoMessage()    {}
func (*SettingsSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4f9d8dd279fffe, []int{0}
}
func (m *SettingsSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsSpec.Unmarshal(m, b)
}
func (m *SettingsSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsSpec.Marshal(b, m, deterministic)
}
func (m *SettingsSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsSpec.Merge(m, src)
}
func (m *SettingsSpec) XXX_Size() int {
	return xxx_messageInfo_SettingsSpec.Size(m)
}
func (m *SettingsSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsSpec proto.InternalMessageInfo

func (m *SettingsSpec) GetMtls() *v1alpha2.TrafficPolicySpec_MTLS {
	if m != nil {
		return m.Mtls
	}
	return nil
}

type SettingsStatus struct {
	// The most recent generation observed in the the Settings metadata.
	// If the observedGeneration does not match generation, the controller has not processed the most
	// recent version of this resource.
	ObservedGeneration int64 `protobuf:"varint,1,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	// The state of the overall resource.
	// It will only show accepted if no processing errors encountered.
	State v1alpha2.ApprovalState `protobuf:"varint,2,opt,name=state,proto3,enum=networking.smh.solo.io.ApprovalState" json:"state,omitempty"`
	// Any errors encountered while processing Settings object.
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsStatus) Reset()         { *m = SettingsStatus{} }
func (m *SettingsStatus) String() string { return proto.CompactTextString(m) }
func (*SettingsStatus) ProtoMessage()    {}
func (*SettingsStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a4f9d8dd279fffe, []int{1}
}
func (m *SettingsStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsStatus.Unmarshal(m, b)
}
func (m *SettingsStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsStatus.Marshal(b, m, deterministic)
}
func (m *SettingsStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsStatus.Merge(m, src)
}
func (m *SettingsStatus) XXX_Size() int {
	return xxx_messageInfo_SettingsStatus.Size(m)
}
func (m *SettingsStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsStatus proto.InternalMessageInfo

func (m *SettingsStatus) GetObservedGeneration() int64 {
	if m != nil {
		return m.ObservedGeneration
	}
	return 0
}

func (m *SettingsStatus) GetState() v1alpha2.ApprovalState {
	if m != nil {
		return m.State
	}
	return v1alpha2.ApprovalState_PENDING
}

func (m *SettingsStatus) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*SettingsSpec)(nil), "settings.smh.solo.io.SettingsSpec")
	proto.RegisterType((*SettingsStatus)(nil), "settings.smh.solo.io.SettingsStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/service-mesh-hub/api/settings/v1alpha2/settings.proto", fileDescriptor_9a4f9d8dd279fffe)
}

var fileDescriptor_9a4f9d8dd279fffe = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x59, 0xab, 0x05, 0xa3, 0xf4, 0xb0, 0x16, 0x29, 0x3d, 0x48, 0x29, 0x08, 0xbd, 0x34,
	0xc1, 0x7a, 0x14, 0x11, 0x7b, 0x51, 0x41, 0x51, 0xb6, 0x3d, 0x79, 0x29, 0xd9, 0x6d, 0x9a, 0x0d,
	0xcd, 0xee, 0x84, 0x64, 0xba, 0xe2, 0x8b, 0xf8, 0x0c, 0x3e, 0x97, 0x4f, 0x22, 0x9b, 0xad, 0xdb,
	0x0a, 0x0a, 0xbd, 0x65, 0x32, 0xf3, 0xfd, 0xbe, 0xf9, 0x43, 0xee, 0xa5, 0xc2, 0x74, 0x15, 0xd3,
	0x04, 0x32, 0xe6, 0x40, 0xc3, 0x50, 0x01, 0x73, 0xc2, 0x16, 0x2a, 0x11, 0xc3, 0x4c, 0xb8, 0x74,
	0x98, 0xae, 0x62, 0xc6, 0x8d, 0x62, 0x4e, 0x20, 0xaa, 0x5c, 0x3a, 0x56, 0x5c, 0x70, 0x6d, 0x52,
	0x3e, 0xaa, 0x7f, 0xa8, 0xb1, 0x80, 0x10, 0xb6, 0xeb, 0xd8, 0x65, 0x29, 0x2d, 0x59, 0x54, 0x41,
	0xb7, 0x2d, 0x41, 0x82, 0x2f, 0x60, 0xe5, 0xab, 0xaa, 0xed, 0xde, 0xfc, 0x69, 0x91, 0x0b, 0x7c,
	0x03, 0xbb, 0x54, 0xb9, 0xdc, 0x98, 0x14, 0x5c, 0xab, 0x39, 0x47, 0x05, 0xf9, 0xcc, 0x21, 0x47,
	0xb1, 0x06, 0x5c, 0xef, 0x0c, 0x40, 0xcb, 0x17, 0x0b, 0x95, 0xcc, 0x0c, 0x68, 0x95, 0xbc, 0x57,
	0xf2, 0x7e, 0x44, 0x8e, 0x27, 0xeb, 0x6e, 0x27, 0x46, 0x24, 0xe1, 0x98, 0xec, 0x67, 0xa8, 0x5d,
	0x27, 0xe8, 0x05, 0x83, 0xa3, 0x11, 0xa5, 0x1b, 0xd0, 0xf6, 0x30, 0x74, 0x5a, 0xb1, 0x5e, 0x3c,
	0xaa, 0x14, 0xd2, 0xa7, 0xe9, 0xe3, 0x24, 0xf2, 0xda, 0xfe, 0x47, 0x40, 0x5a, 0x35, 0x14, 0x39,
	0xae, 0x5c, 0xc8, 0xc8, 0x09, 0xc4, 0x65, 0xa7, 0x62, 0x3e, 0x93, 0x22, 0x17, 0xd6, 0x0f, 0xe2,
	0x5d, 0x1a, 0x51, 0xf8, 0x93, 0xba, 0xab, 0x33, 0xe1, 0x15, 0x39, 0xf0, 0x53, 0x76, 0xf6, 0x7a,
	0xc1, 0xa0, 0x35, 0x3a, 0xff, 0xaf, 0x91, 0x5b, 0x63, 0x2c, 0x14, 0x5c, 0x97, 0x3e, 0x22, 0xaa,
	0x34, 0xe1, 0x29, 0x69, 0x0a, 0x6b, 0xc1, 0xba, 0x4e, 0xa3, 0xd7, 0x18, 0x1c, 0x46, 0xeb, 0x68,
	0xfc, 0xfc, 0xf9, 0x75, 0x16, 0xbc, 0x3e, 0xec, 0x72, 0x68, 0xb3, 0x94, 0xbf, 0x8e, 0xbd, 0x6d,
	0x5a, 0xaf, 0x34, 0x6e, 0xfa, 0x25, 0x5e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x0d, 0x93,
	0x78, 0x3c, 0x02, 0x00, 0x00,
}

func (this *SettingsSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SettingsSpec)
	if !ok {
		that2, ok := that.(SettingsSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Mtls.Equal(that1.Mtls) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *SettingsStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SettingsStatus)
	if !ok {
		that2, ok := that.(SettingsStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ObservedGeneration != that1.ObservedGeneration {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if len(this.Errors) != len(that1.Errors) {
		return false
	}
	for i := range this.Errors {
		if this.Errors[i] != that1.Errors[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
