// Code generated by skv2. DO NOT EDIT.

//go:generate mockgen -source ./snapshot.go -destination mocks/snapshot.go

// The Input Snapshot contains the set of all:
// * TrafficTargets
// * Workloads
// * Meshes
// * TrafficPolicies
// * AccessPolicies
// * VirtualMeshes
// * FailoverServices
// * Secrets
// * KubernetesClusters
// read from a given cluster or set of clusters, across all namespaces.
//
// A snapshot can be constructed from either a single Manager (for a single cluster)
// or a ClusterWatcher (for multiple clusters) using the SnapshotBuilder.
//
// Resources in a MultiCluster snapshot will have their ClusterName set to the
// name of the cluster from which the resource was read.

package input

import (
	"context"
	"encoding/json"

	"github.com/solo-io/go-utils/contextutils"
	"k8s.io/apimachinery/pkg/api/errors"

	"github.com/rotisserie/eris"
	apiextensions_k8s_io_v1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"

	"github.com/hashicorp/go-multierror"
	"github.com/solo-io/skv2/pkg/controllerutils"
	"github.com/solo-io/skv2/pkg/multicluster"
	"sigs.k8s.io/controller-runtime/pkg/client"

	discovery_smh_solo_io_v1alpha2 "github.com/solo-io/service-mesh-hub/pkg/api/discovery.smh.solo.io/v1alpha2"
	discovery_smh_solo_io_v1alpha2_sets "github.com/solo-io/service-mesh-hub/pkg/api/discovery.smh.solo.io/v1alpha2/sets"

	networking_smh_solo_io_v1alpha2 "github.com/solo-io/service-mesh-hub/pkg/api/networking.smh.solo.io/v1alpha2"
	networking_smh_solo_io_v1alpha2_sets "github.com/solo-io/service-mesh-hub/pkg/api/networking.smh.solo.io/v1alpha2/sets"

	v1 "github.com/solo-io/external-apis/pkg/api/k8s/core/v1"
	v1_sets "github.com/solo-io/external-apis/pkg/api/k8s/core/v1/sets"

	multicluster_solo_io_v1alpha1 "github.com/solo-io/skv2/pkg/api/multicluster.solo.io/v1alpha1"
	multicluster_solo_io_v1alpha1_sets "github.com/solo-io/skv2/pkg/api/multicluster.solo.io/v1alpha1/sets"
)

// the snapshot of input resources consumed by translation
type Snapshot interface {

	// return the set of input TrafficTargets
	TrafficTargets() discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet
	// return the set of input Workloads
	Workloads() discovery_smh_solo_io_v1alpha2_sets.WorkloadSet
	// return the set of input Meshes
	Meshes() discovery_smh_solo_io_v1alpha2_sets.MeshSet

	// return the set of input TrafficPolicies
	TrafficPolicies() networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet
	// return the set of input AccessPolicies
	AccessPolicies() networking_smh_solo_io_v1alpha2_sets.AccessPolicySet
	// return the set of input VirtualMeshes
	VirtualMeshes() networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet
	// return the set of input FailoverServices
	FailoverServices() networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet

	// return the set of input Secrets
	Secrets() v1_sets.SecretSet

	// return the set of input KubernetesClusters
	KubernetesClusters() multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet
	// update the status of all input objects which support
	// the Status subresource (in the local cluster)
	SyncStatuses(ctx context.Context, c client.Client) error

	// update the status of all input objects which support
	// the Status subresource (across multiple clusters)
	SyncStatusesMultiCluster(ctx context.Context, mcClient multicluster.Client) error
	// serialize the entire snapshot as JSON
	MarshalJSON() ([]byte, error)
}

type snapshot struct {
	name string

	trafficTargets discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet
	workloads      discovery_smh_solo_io_v1alpha2_sets.WorkloadSet
	meshes         discovery_smh_solo_io_v1alpha2_sets.MeshSet

	trafficPolicies  networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet
	accessPolicies   networking_smh_solo_io_v1alpha2_sets.AccessPolicySet
	virtualMeshes    networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet
	failoverServices networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet

	secrets v1_sets.SecretSet

	kubernetesClusters multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet
}

func NewSnapshot(
	name string,

	trafficTargets discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet,
	workloads discovery_smh_solo_io_v1alpha2_sets.WorkloadSet,
	meshes discovery_smh_solo_io_v1alpha2_sets.MeshSet,

	trafficPolicies networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet,
	accessPolicies networking_smh_solo_io_v1alpha2_sets.AccessPolicySet,
	virtualMeshes networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet,
	failoverServices networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet,

	secrets v1_sets.SecretSet,

	kubernetesClusters multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet,

) Snapshot {
	return &snapshot{
		name: name,

		trafficTargets:     trafficTargets,
		workloads:          workloads,
		meshes:             meshes,
		trafficPolicies:    trafficPolicies,
		accessPolicies:     accessPolicies,
		virtualMeshes:      virtualMeshes,
		failoverServices:   failoverServices,
		secrets:            secrets,
		kubernetesClusters: kubernetesClusters,
	}
}

func (s snapshot) TrafficTargets() discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet {
	return s.trafficTargets
}

func (s snapshot) Workloads() discovery_smh_solo_io_v1alpha2_sets.WorkloadSet {
	return s.workloads
}

func (s snapshot) Meshes() discovery_smh_solo_io_v1alpha2_sets.MeshSet {
	return s.meshes
}

func (s snapshot) TrafficPolicies() networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet {
	return s.trafficPolicies
}

func (s snapshot) AccessPolicies() networking_smh_solo_io_v1alpha2_sets.AccessPolicySet {
	return s.accessPolicies
}

func (s snapshot) VirtualMeshes() networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet {
	return s.virtualMeshes
}

func (s snapshot) FailoverServices() networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet {
	return s.failoverServices
}

func (s snapshot) Secrets() v1_sets.SecretSet {
	return s.secrets
}

func (s snapshot) KubernetesClusters() multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet {
	return s.kubernetesClusters
}
func (s snapshot) SyncStatuses(ctx context.Context, c client.Client) error {

	for _, obj := range s.TrafficTargets().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.Workloads().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.Meshes().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}

	for _, obj := range s.TrafficPolicies().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.AccessPolicies().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.VirtualMeshes().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.FailoverServices().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}

	for _, obj := range s.KubernetesClusters().List() {
		if _, err := controllerutils.UpdateStatus(ctx, c, obj); err != nil {
			return err
		}
	}
	return nil
}

func (s snapshot) SyncStatusesMultiCluster(ctx context.Context, mcClient multicluster.Client) error {

	for _, obj := range s.TrafficTargets().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.Workloads().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.Meshes().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}

	for _, obj := range s.TrafficPolicies().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.AccessPolicies().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.VirtualMeshes().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	for _, obj := range s.FailoverServices().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}

	for _, obj := range s.KubernetesClusters().List() {
		clusterClient, err := mcClient.Cluster(obj.ClusterName)
		if err != nil {
			return err
		}
		if _, err := controllerutils.UpdateStatus(ctx, clusterClient, obj); err != nil {
			return err
		}
	}
	return nil
}

func (s snapshot) MarshalJSON() ([]byte, error) {
	snapshotMap := map[string]interface{}{"name": s.name}

	snapshotMap["trafficTargets"] = s.trafficTargets.List()
	snapshotMap["workloads"] = s.workloads.List()
	snapshotMap["meshes"] = s.meshes.List()
	snapshotMap["trafficPolicies"] = s.trafficPolicies.List()
	snapshotMap["accessPolicies"] = s.accessPolicies.List()
	snapshotMap["virtualMeshes"] = s.virtualMeshes.List()
	snapshotMap["failoverServices"] = s.failoverServices.List()
	snapshotMap["secrets"] = s.secrets.List()
	snapshotMap["kubernetesClusters"] = s.kubernetesClusters.List()
	return json.Marshal(snapshotMap)
}

// builds the input snapshot from API Clients.
// Two types of builders are available:
// a builder for snapshots of resources across multiple clusters
// a builder for snapshots of resources within a single cluster
type Builder interface {
	BuildSnapshot(ctx context.Context, name string, opts BuildOptions) (Snapshot, error)
}

// Options for building a snapshot
type BuildOptions struct {

	// List options for composing a snapshot from TrafficTargets
	TrafficTargets TrafficTargetBuildOptions
	// List options for composing a snapshot from Workloads
	Workloads WorkloadBuildOptions
	// List options for composing a snapshot from Meshes
	Meshes MeshBuildOptions

	// List options for composing a snapshot from TrafficPolicies
	TrafficPolicies TrafficPolicyBuildOptions
	// List options for composing a snapshot from AccessPolicies
	AccessPolicies AccessPolicyBuildOptions
	// List options for composing a snapshot from VirtualMeshes
	VirtualMeshes VirtualMeshBuildOptions
	// List options for composing a snapshot from FailoverServices
	FailoverServices FailoverServiceBuildOptions

	// List options for composing a snapshot from Secrets
	Secrets SecretBuildOptions

	// List options for composing a snapshot from KubernetesClusters
	KubernetesClusters KubernetesClusterBuildOptions
}

type CrdCheckOption int

const (
	// skip checking whether a crd exists for a kind before reading it from a cluster
	CrdCheckOption_SkipCheck CrdCheckOption = iota

	// return an error if the crd does not exist for a kind before reading it from the cluster
	CrdCheckOption_ErrorIfNotPresent

	// log an error (and continue) if the crd does not exist for a kind before reading it from the cluster
	CrdCheckOption_WarnIfNotPresent

	// ignore error (and continue) if the crd does not exist for a kind before reading it from the cluster
	CrdCheckOption_IgnoreIfNotPresent
)

// Options for reading TrafficTargets
type TrafficTargetBuildOptions struct {

	// List options for composing a snapshot from TrafficTargets
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading TrafficTargets.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading Workloads
type WorkloadBuildOptions struct {

	// List options for composing a snapshot from Workloads
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading Workloads.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading Meshes
type MeshBuildOptions struct {

	// List options for composing a snapshot from Meshes
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading Meshes.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading TrafficPolicies
type TrafficPolicyBuildOptions struct {

	// List options for composing a snapshot from TrafficPolicies
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading TrafficPolicies.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading AccessPolicies
type AccessPolicyBuildOptions struct {

	// List options for composing a snapshot from AccessPolicies
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading AccessPolicies.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading VirtualMeshes
type VirtualMeshBuildOptions struct {

	// List options for composing a snapshot from VirtualMeshes
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading VirtualMeshes.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading FailoverServices
type FailoverServiceBuildOptions struct {

	// List options for composing a snapshot from FailoverServices
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading FailoverServices.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading Secrets
type SecretBuildOptions struct {

	// List options for composing a snapshot from Secrets
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading Secrets.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// Options for reading KubernetesClusters
type KubernetesClusterBuildOptions struct {

	// List options for composing a snapshot from KubernetesClusters
	ListOptions []client.ListOption

	// Verify the existence of the corresponding CRD before reading KubernetesClusters.
	// Choose a CrdCheckOption that fits your use case.
	CrdCheck CrdCheckOption
}

// build a snapshot from resources across multiple clusters
type multiClusterBuilder struct {
	clusters multicluster.ClusterSet
	client   multicluster.Client
}

// Produces snapshots of resources across all clusters defined in the ClusterSet
func NewMultiClusterBuilder(
	clusters multicluster.ClusterSet,
	client multicluster.Client,
) Builder {
	return &multiClusterBuilder{
		clusters: clusters,
		client:   client,
	}
}

func (b *multiClusterBuilder) BuildSnapshot(ctx context.Context, name string, opts BuildOptions) (Snapshot, error) {

	trafficTargets := discovery_smh_solo_io_v1alpha2_sets.NewTrafficTargetSet()
	workloads := discovery_smh_solo_io_v1alpha2_sets.NewWorkloadSet()
	meshes := discovery_smh_solo_io_v1alpha2_sets.NewMeshSet()

	trafficPolicies := networking_smh_solo_io_v1alpha2_sets.NewTrafficPolicySet()
	accessPolicies := networking_smh_solo_io_v1alpha2_sets.NewAccessPolicySet()
	virtualMeshes := networking_smh_solo_io_v1alpha2_sets.NewVirtualMeshSet()
	failoverServices := networking_smh_solo_io_v1alpha2_sets.NewFailoverServiceSet()

	secrets := v1_sets.NewSecretSet()

	kubernetesClusters := multicluster_solo_io_v1alpha1_sets.NewKubernetesClusterSet()

	var errs error

	for _, cluster := range b.clusters.ListClusters() {

		if err := b.insertTrafficTargetsFromCluster(ctx, cluster, trafficTargets, opts.TrafficTargets); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertWorkloadsFromCluster(ctx, cluster, workloads, opts.Workloads); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertMeshesFromCluster(ctx, cluster, meshes, opts.Meshes); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertTrafficPoliciesFromCluster(ctx, cluster, trafficPolicies, opts.TrafficPolicies); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertAccessPoliciesFromCluster(ctx, cluster, accessPolicies, opts.AccessPolicies); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertVirtualMeshesFromCluster(ctx, cluster, virtualMeshes, opts.VirtualMeshes); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertFailoverServicesFromCluster(ctx, cluster, failoverServices, opts.FailoverServices); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertSecretsFromCluster(ctx, cluster, secrets, opts.Secrets); err != nil {
			errs = multierror.Append(errs, err)
		}
		if err := b.insertKubernetesClustersFromCluster(ctx, cluster, kubernetesClusters, opts.KubernetesClusters); err != nil {
			errs = multierror.Append(errs, err)
		}

	}

	outputSnap := NewSnapshot(
		name,

		trafficTargets,
		workloads,
		meshes,
		trafficPolicies,
		accessPolicies,
		virtualMeshes,
		failoverServices,
		secrets,
		kubernetesClusters,
	)

	return outputSnap, errs
}

func (b *multiClusterBuilder) insertTrafficTargetsFromCluster(ctx context.Context, cluster string, trafficTargets discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet, opts TrafficTargetBuildOptions) error {
	trafficTargetClient, err := discovery_smh_solo_io_v1alpha2.NewMulticlusterTrafficTargetClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "traffictargets."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	trafficTargetList, err := trafficTargetClient.ListTrafficTarget(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range trafficTargetList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		trafficTargets.Insert(&item)
	}

	return nil
}
func (b *multiClusterBuilder) insertWorkloadsFromCluster(ctx context.Context, cluster string, workloads discovery_smh_solo_io_v1alpha2_sets.WorkloadSet, opts WorkloadBuildOptions) error {
	workloadClient, err := discovery_smh_solo_io_v1alpha2.NewMulticlusterWorkloadClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "workloads."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	workloadList, err := workloadClient.ListWorkload(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range workloadList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		workloads.Insert(&item)
	}

	return nil
}
func (b *multiClusterBuilder) insertMeshesFromCluster(ctx context.Context, cluster string, meshes discovery_smh_solo_io_v1alpha2_sets.MeshSet, opts MeshBuildOptions) error {
	meshClient, err := discovery_smh_solo_io_v1alpha2.NewMulticlusterMeshClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "meshes."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	meshList, err := meshClient.ListMesh(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range meshList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		meshes.Insert(&item)
	}

	return nil
}

func (b *multiClusterBuilder) insertTrafficPoliciesFromCluster(ctx context.Context, cluster string, trafficPolicies networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet, opts TrafficPolicyBuildOptions) error {
	trafficPolicyClient, err := networking_smh_solo_io_v1alpha2.NewMulticlusterTrafficPolicyClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "trafficpolicies."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	trafficPolicyList, err := trafficPolicyClient.ListTrafficPolicy(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range trafficPolicyList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		trafficPolicies.Insert(&item)
	}

	return nil
}
func (b *multiClusterBuilder) insertAccessPoliciesFromCluster(ctx context.Context, cluster string, accessPolicies networking_smh_solo_io_v1alpha2_sets.AccessPolicySet, opts AccessPolicyBuildOptions) error {
	accessPolicyClient, err := networking_smh_solo_io_v1alpha2.NewMulticlusterAccessPolicyClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "accesspolicies."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	accessPolicyList, err := accessPolicyClient.ListAccessPolicy(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range accessPolicyList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		accessPolicies.Insert(&item)
	}

	return nil
}
func (b *multiClusterBuilder) insertVirtualMeshesFromCluster(ctx context.Context, cluster string, virtualMeshes networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet, opts VirtualMeshBuildOptions) error {
	virtualMeshClient, err := networking_smh_solo_io_v1alpha2.NewMulticlusterVirtualMeshClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "virtualmeshes."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	virtualMeshList, err := virtualMeshClient.ListVirtualMesh(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range virtualMeshList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		virtualMeshes.Insert(&item)
	}

	return nil
}
func (b *multiClusterBuilder) insertFailoverServicesFromCluster(ctx context.Context, cluster string, failoverServices networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet, opts FailoverServiceBuildOptions) error {
	failoverServiceClient, err := networking_smh_solo_io_v1alpha2.NewMulticlusterFailoverServiceClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "failoverservices."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	failoverServiceList, err := failoverServiceClient.ListFailoverService(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range failoverServiceList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		failoverServices.Insert(&item)
	}

	return nil
}

func (b *multiClusterBuilder) insertSecretsFromCluster(ctx context.Context, cluster string, secrets v1_sets.SecretSet, opts SecretBuildOptions) error {
	secretClient, err := v1.NewMulticlusterSecretClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "secrets."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	secretList, err := secretClient.ListSecret(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range secretList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		secrets.Insert(&item)
	}

	return nil
}

func (b *multiClusterBuilder) insertKubernetesClustersFromCluster(ctx context.Context, cluster string, kubernetesClusters multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet, opts KubernetesClusterBuildOptions) error {
	kubernetesClusterClient, err := multicluster_solo_io_v1alpha1.NewMulticlusterKubernetesClusterClient(b.client).Cluster(cluster)
	if err != nil {
		return err
	}

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		cli, err := b.client.Cluster(cluster)
		if err != nil {
			return err
		}
		crdName := "kubernetesclusters."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, cli, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	kubernetesClusterList, err := kubernetesClusterClient.ListKubernetesCluster(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range kubernetesClusterList.Items {
		item := item               // pike
		item.ClusterName = cluster // set cluster for in-memory processing
		kubernetesClusters.Insert(&item)
	}

	return nil
}

// build a snapshot from resources in a single cluster
type singleClusterBuilder struct {
	client client.Client
}

// Produces snapshots of resources across all clusters defined in the ClusterSet
func NewSingleClusterBuilder(
	client client.Client,
) Builder {
	return &singleClusterBuilder{
		client: client,
	}
}

func (b *singleClusterBuilder) BuildSnapshot(ctx context.Context, name string, opts BuildOptions) (Snapshot, error) {

	trafficTargets := discovery_smh_solo_io_v1alpha2_sets.NewTrafficTargetSet()
	workloads := discovery_smh_solo_io_v1alpha2_sets.NewWorkloadSet()
	meshes := discovery_smh_solo_io_v1alpha2_sets.NewMeshSet()

	trafficPolicies := networking_smh_solo_io_v1alpha2_sets.NewTrafficPolicySet()
	accessPolicies := networking_smh_solo_io_v1alpha2_sets.NewAccessPolicySet()
	virtualMeshes := networking_smh_solo_io_v1alpha2_sets.NewVirtualMeshSet()
	failoverServices := networking_smh_solo_io_v1alpha2_sets.NewFailoverServiceSet()

	secrets := v1_sets.NewSecretSet()

	kubernetesClusters := multicluster_solo_io_v1alpha1_sets.NewKubernetesClusterSet()

	var errs error

	if err := b.insertTrafficTargets(ctx, trafficTargets, opts.TrafficTargets); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertWorkloads(ctx, workloads, opts.Workloads); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertMeshes(ctx, meshes, opts.Meshes); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertTrafficPolicies(ctx, trafficPolicies, opts.TrafficPolicies); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertAccessPolicies(ctx, accessPolicies, opts.AccessPolicies); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertVirtualMeshes(ctx, virtualMeshes, opts.VirtualMeshes); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertFailoverServices(ctx, failoverServices, opts.FailoverServices); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertSecrets(ctx, secrets, opts.Secrets); err != nil {
		errs = multierror.Append(errs, err)
	}
	if err := b.insertKubernetesClusters(ctx, kubernetesClusters, opts.KubernetesClusters); err != nil {
		errs = multierror.Append(errs, err)
	}

	outputSnap := NewSnapshot(
		name,

		trafficTargets,
		workloads,
		meshes,
		trafficPolicies,
		accessPolicies,
		virtualMeshes,
		failoverServices,
		secrets,
		kubernetesClusters,
	)

	return outputSnap, errs
}

func (b *singleClusterBuilder) insertTrafficTargets(ctx context.Context, trafficTargets discovery_smh_solo_io_v1alpha2_sets.TrafficTargetSet, opts TrafficTargetBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "traffictargets."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	trafficTargetList, err := discovery_smh_solo_io_v1alpha2.NewTrafficTargetClient(b.client).ListTrafficTarget(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range trafficTargetList.Items {
		item := item // pike
		trafficTargets.Insert(&item)
	}

	return nil
}
func (b *singleClusterBuilder) insertWorkloads(ctx context.Context, workloads discovery_smh_solo_io_v1alpha2_sets.WorkloadSet, opts WorkloadBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "workloads."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	workloadList, err := discovery_smh_solo_io_v1alpha2.NewWorkloadClient(b.client).ListWorkload(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range workloadList.Items {
		item := item // pike
		workloads.Insert(&item)
	}

	return nil
}
func (b *singleClusterBuilder) insertMeshes(ctx context.Context, meshes discovery_smh_solo_io_v1alpha2_sets.MeshSet, opts MeshBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "meshes."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	meshList, err := discovery_smh_solo_io_v1alpha2.NewMeshClient(b.client).ListMesh(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range meshList.Items {
		item := item // pike
		meshes.Insert(&item)
	}

	return nil
}

func (b *singleClusterBuilder) insertTrafficPolicies(ctx context.Context, trafficPolicies networking_smh_solo_io_v1alpha2_sets.TrafficPolicySet, opts TrafficPolicyBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "trafficpolicies."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	trafficPolicyList, err := networking_smh_solo_io_v1alpha2.NewTrafficPolicyClient(b.client).ListTrafficPolicy(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range trafficPolicyList.Items {
		item := item // pike
		trafficPolicies.Insert(&item)
	}

	return nil
}
func (b *singleClusterBuilder) insertAccessPolicies(ctx context.Context, accessPolicies networking_smh_solo_io_v1alpha2_sets.AccessPolicySet, opts AccessPolicyBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "accesspolicies."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	accessPolicyList, err := networking_smh_solo_io_v1alpha2.NewAccessPolicyClient(b.client).ListAccessPolicy(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range accessPolicyList.Items {
		item := item // pike
		accessPolicies.Insert(&item)
	}

	return nil
}
func (b *singleClusterBuilder) insertVirtualMeshes(ctx context.Context, virtualMeshes networking_smh_solo_io_v1alpha2_sets.VirtualMeshSet, opts VirtualMeshBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "virtualmeshes."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	virtualMeshList, err := networking_smh_solo_io_v1alpha2.NewVirtualMeshClient(b.client).ListVirtualMesh(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range virtualMeshList.Items {
		item := item // pike
		virtualMeshes.Insert(&item)
	}

	return nil
}
func (b *singleClusterBuilder) insertFailoverServices(ctx context.Context, failoverServices networking_smh_solo_io_v1alpha2_sets.FailoverServiceSet, opts FailoverServiceBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "failoverservices."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	failoverServiceList, err := networking_smh_solo_io_v1alpha2.NewFailoverServiceClient(b.client).ListFailoverService(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range failoverServiceList.Items {
		item := item // pike
		failoverServices.Insert(&item)
	}

	return nil
}

func (b *singleClusterBuilder) insertSecrets(ctx context.Context, secrets v1_sets.SecretSet, opts SecretBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "secrets."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	secretList, err := v1.NewSecretClient(b.client).ListSecret(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range secretList.Items {
		item := item // pike
		secrets.Insert(&item)
	}

	return nil
}

func (b *singleClusterBuilder) insertKubernetesClusters(ctx context.Context, kubernetesClusters multicluster_solo_io_v1alpha1_sets.KubernetesClusterSet, opts KubernetesClusterBuildOptions) error {

	if opts.CrdCheck != CrdCheckOption_SkipCheck {
		// verify CRD is present for kind
		crdName := "kubernetesclusters."
		crdVersion := ""
		if checkFailed, err := verifyCrdExists(ctx, b.client, crdName, crdVersion); err != nil {
			if checkFailed {
				return eris.Wrap(err, "crd check failed")
			}
			switch opts.CrdCheck {
			case CrdCheckOption_WarnIfNotPresent:
				contextutils.LoggerFrom(ctx).Warnf("crd %v not registered (fetch err: %v)", crdName, err)
				return nil
			case CrdCheckOption_IgnoreIfNotPresent:
				return nil
			case CrdCheckOption_ErrorIfNotPresent:
				return err
			}
		}
	}

	kubernetesClusterList, err := multicluster_solo_io_v1alpha1.NewKubernetesClusterClient(b.client).ListKubernetesCluster(ctx, opts.ListOptions...)
	if err != nil {
		return err
	}

	for _, item := range kubernetesClusterList.Items {
		item := item // pike
		kubernetesClusters.Insert(&item)
	}

	return nil
}

func verifyCrdExists(ctx context.Context, c client.Client, crdName, crdVersion string) (bool, error) {
	var crd apiextensions_k8s_io_v1beta1.CustomResourceDefinition
	if err := c.Get(ctx, client.ObjectKey{Name: crdName}, &crd); err != nil {
		checkFailed := !errors.IsNotFound(err)
		return checkFailed, err
	}
	for _, version := range crd.Spec.Versions {
		if version.Name == crdVersion {
			return false, nil
		}
	}
	return false, eris.Errorf("version %v not found for crd %v", crdVersion, crdName)
}
