steps:
# Dep is produced from a private cloud-builders repo
- name: 'soloio/dep'
  args: ['ensure']
  env: ['PROJECT_ROOT=github.com/solo-io/supergloo']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'supergloo', 'github.com/solo-io/supergloo/cmd']
  env: ['PROJECT_ROOT=github.com/solo-io/supergloo']


artifacts:
  objects:
    location: 'gs://artifacts.solo.io/'
    paths: ['supergloo']
