// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/service-mesh-hub/api/networking/v1alpha2/validation_state.proto

package v1alpha2

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/solo-io/skv2/pkg/api/core.skv2.solo.io/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State of a Policy resource reflected in the status by Service Mesh Hub while processing a resource.
type ApprovalState int32

const (
	// Resources are in a Pending state before they have been processed by Service Mesh Hub.
	ApprovalState_PENDING ApprovalState = 0
	// Resources are in a Accepted state when they are valid and have been applied successfully to
	// the Service Mesh Hub configuration.
	ApprovalState_ACCEPTED ApprovalState = 1
	// Resources are in an Invalid state when they contain incorrect configuration parameters,
	// such as missing required values or invalid resource references.
	// An invalid state can also result when a resource's configuration is valid
	// but conflicts with another resource which was accepted in an earlier point in time.
	ApprovalState_INVALID ApprovalState = 2
	// Resources are in a Failed state when they contain correct configuration parameters,
	// but the server encountered an error trying to synchronize the system to
	// the desired state.
	ApprovalState_FAILED ApprovalState = 3
)

var ApprovalState_name = map[int32]string{
	0: "PENDING",
	1: "ACCEPTED",
	2: "INVALID",
	3: "FAILED",
}

var ApprovalState_value = map[string]int32{
	"PENDING":  0,
	"ACCEPTED": 1,
	"INVALID":  2,
	"FAILED":   3,
}

func (x ApprovalState) String() string {
	return proto.EnumName(ApprovalState_name, int32(x))
}

func (ApprovalState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3950dd7df1e96ad2, []int{0}
}

// The approval status of a policy that has been applied to a discovery resource.
type ApprovalStatus struct {
	// AcceptanceOrder represents the order in which the Policy
	// was accepted and applied to a discovery resource. The first accepted policy
	// will have an acceptance_order of 0, the second 1, etc.
	// When conflicts are detected in the system,
	// the Policy with the lowest acceptance_order
	// will be chosen (and all other conflicting policies will be rejected).
	AcceptanceOrder uint32 `protobuf:"varint,1,opt,name=acceptance_order,json=acceptanceOrder,proto3" json:"acceptance_order,omitempty"`
	// The result of attempting to apply the policy to the discovery resource,
	// reported by the Policy controller (mesh-networking).
	State ApprovalState `protobuf:"varint,2,opt,name=state,proto3,enum=networking.smh.solo.io.ApprovalState" json:"state,omitempty"`
	// Any errors observed which prevented the resource from being Accepted.
	Errors               []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApprovalStatus) Reset()         { *m = ApprovalStatus{} }
func (m *ApprovalStatus) String() string { return proto.CompactTextString(m) }
func (*ApprovalStatus) ProtoMessage()    {}
func (*ApprovalStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3950dd7df1e96ad2, []int{0}
}
func (m *ApprovalStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovalStatus.Unmarshal(m, b)
}
func (m *ApprovalStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovalStatus.Marshal(b, m, deterministic)
}
func (m *ApprovalStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovalStatus.Merge(m, src)
}
func (m *ApprovalStatus) XXX_Size() int {
	return xxx_messageInfo_ApprovalStatus.Size(m)
}
func (m *ApprovalStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovalStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovalStatus proto.InternalMessageInfo

func (m *ApprovalStatus) GetAcceptanceOrder() uint32 {
	if m != nil {
		return m.AcceptanceOrder
	}
	return 0
}

func (m *ApprovalStatus) GetState() ApprovalState {
	if m != nil {
		return m.State
	}
	return ApprovalState_PENDING
}

func (m *ApprovalStatus) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterEnum("networking.smh.solo.io.ApprovalState", ApprovalState_name, ApprovalState_value)
	proto.RegisterType((*ApprovalStatus)(nil), "networking.smh.solo.io.ApprovalStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/service-mesh-hub/api/networking/v1alpha2/validation_state.proto", fileDescriptor_3950dd7df1e96ad2)
}

var fileDescriptor_3950dd7df1e96ad2 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xb5, 0x1b, 0x4e, 0x8d, 0x6e, 0x96, 0x20, 0x63, 0x4c, 0x90, 0x21, 0x08, 0x53, 0x58, 0xc2,
	0xe6, 0xa3, 0x4f, 0x75, 0xad, 0x52, 0x1c, 0x73, 0x56, 0xf1, 0xc1, 0x97, 0x91, 0x75, 0xa1, 0x0d,
	0xeb, 0x7a, 0x43, 0x92, 0xd5, 0xdf, 0xf0, 0x33, 0xfc, 0x2e, 0xbf, 0x44, 0xda, 0x8a, 0x9b, 0xe2,
	0x83, 0x4f, 0xb9, 0x39, 0xb9, 0xe7, 0xe4, 0x70, 0x0e, 0x0a, 0x22, 0x61, 0xe2, 0xd5, 0x8c, 0x84,
	0xb0, 0xa4, 0x1a, 0x12, 0xe8, 0x09, 0xa0, 0x9a, 0xab, 0x4c, 0x84, 0xbc, 0xb7, 0xe4, 0x3a, 0xee,
	0xc5, 0xab, 0x19, 0x65, 0x52, 0xd0, 0x94, 0x9b, 0x57, 0x50, 0x0b, 0x91, 0x46, 0x34, 0xeb, 0xb3,
	0x44, 0xc6, 0x6c, 0x40, 0x33, 0x96, 0x88, 0x39, 0x33, 0x02, 0xd2, 0xa9, 0x36, 0xcc, 0x70, 0x22,
	0x15, 0x18, 0xc0, 0xcd, 0xf5, 0x2e, 0xd1, 0xcb, 0x98, 0xe4, 0xba, 0x44, 0x40, 0xfb, 0x58, 0x2f,
	0xb2, 0x41, 0x21, 0x16, 0x82, 0xe2, 0x34, 0xeb, 0x17, 0x67, 0x49, 0x6a, 0x1f, 0x45, 0x10, 0x41,
	0x31, 0xd2, 0x7c, 0x2a, 0xd1, 0xd3, 0x37, 0x0b, 0x35, 0x1c, 0x29, 0x15, 0x64, 0x2c, 0x79, 0x34,
	0xcc, 0xac, 0x34, 0x3e, 0x47, 0x36, 0x0b, 0x43, 0x2e, 0x0d, 0x4b, 0x43, 0x3e, 0x05, 0x35, 0xe7,
	0xaa, 0x65, 0x75, 0xac, 0x6e, 0x3d, 0x38, 0x5c, 0xe3, 0xf7, 0x39, 0x8c, 0xaf, 0xd0, 0x76, 0xe1,
	0xab, 0x55, 0xe9, 0x58, 0xdd, 0xc6, 0xe0, 0x8c, 0xfc, 0x6d, 0x8c, 0x6c, 0xfe, 0xc0, 0x83, 0x92,
	0x83, 0x9b, 0xa8, 0xc6, 0x95, 0x02, 0xa5, 0x5b, 0xd5, 0x4e, 0xb5, 0xbb, 0x17, 0x7c, 0xdd, 0x2e,
	0x86, 0xa8, 0xfe, 0x63, 0x1f, 0xef, 0xa3, 0x9d, 0x89, 0x37, 0x76, 0xfd, 0xf1, 0xad, 0xbd, 0x85,
	0x0f, 0xd0, 0xae, 0x33, 0x1c, 0x7a, 0x93, 0x27, 0xcf, 0xb5, 0xad, 0xfc, 0xc9, 0x1f, 0x3f, 0x3b,
	0x23, 0xdf, 0xb5, 0x2b, 0x18, 0xa1, 0xda, 0x8d, 0xe3, 0x8f, 0x3c, 0xd7, 0xae, 0x5e, 0x3f, 0xbc,
	0x7f, 0x9c, 0x58, 0x2f, 0x77, 0xff, 0x09, 0x5f, 0x2e, 0xa2, 0x5f, 0x05, 0x6c, 0x7a, 0xff, 0x2e,
	0x63, 0x56, 0x2b, 0x12, 0xbb, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x23, 0xd3, 0x74, 0x24, 0xd2,
	0x01, 0x00, 0x00,
}

func (this *ApprovalStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ApprovalStatus)
	if !ok {
		that2, ok := that.(ApprovalStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AcceptanceOrder != that1.AcceptanceOrder {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if len(this.Errors) != len(that1.Errors) {
		return false
	}
	for i := range this.Errors {
		if this.Errors[i] != that1.Errors[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
