/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/solo-io/mesh-projects/pkg/api/discovery.zephyr.solo.io/v1alpha1"
	scheme "github.com/solo-io/mesh-projects/pkg/api/discovery.zephyr.solo.io/v1alpha1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MeshWorkloadsGetter has a method to return a MeshWorkloadInterface.
// A group's client should implement this interface.
type MeshWorkloadsGetter interface {
	MeshWorkloads(namespace string) MeshWorkloadInterface
}

// MeshWorkloadInterface has methods to work with MeshWorkload resources.
type MeshWorkloadInterface interface {
	Create(*v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error)
	Update(*v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error)
	UpdateStatus(*v1alpha1.MeshWorkload) (*v1alpha1.MeshWorkload, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MeshWorkload, error)
	List(opts v1.ListOptions) (*v1alpha1.MeshWorkloadList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MeshWorkload, err error)
	MeshWorkloadExpansion
}

// meshWorkloads implements MeshWorkloadInterface
type meshWorkloads struct {
	client rest.Interface
	ns     string
}

// newMeshWorkloads returns a MeshWorkloads
func newMeshWorkloads(c *DiscoveryV1alpha1Client, namespace string) *meshWorkloads {
	return &meshWorkloads{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the meshWorkload, and returns the corresponding meshWorkload object, and an error if there is any.
func (c *meshWorkloads) Get(name string, options v1.GetOptions) (result *v1alpha1.MeshWorkload, err error) {
	result = &v1alpha1.MeshWorkload{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("meshworkloads").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MeshWorkloads that match those selectors.
func (c *meshWorkloads) List(opts v1.ListOptions) (result *v1alpha1.MeshWorkloadList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MeshWorkloadList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("meshworkloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested meshWorkloads.
func (c *meshWorkloads) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("meshworkloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a meshWorkload and creates it.  Returns the server's representation of the meshWorkload, and an error, if there is any.
func (c *meshWorkloads) Create(meshWorkload *v1alpha1.MeshWorkload) (result *v1alpha1.MeshWorkload, err error) {
	result = &v1alpha1.MeshWorkload{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("meshworkloads").
		Body(meshWorkload).
		Do().
		Into(result)
	return
}

// Update takes the representation of a meshWorkload and updates it. Returns the server's representation of the meshWorkload, and an error, if there is any.
func (c *meshWorkloads) Update(meshWorkload *v1alpha1.MeshWorkload) (result *v1alpha1.MeshWorkload, err error) {
	result = &v1alpha1.MeshWorkload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("meshworkloads").
		Name(meshWorkload.Name).
		Body(meshWorkload).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *meshWorkloads) UpdateStatus(meshWorkload *v1alpha1.MeshWorkload) (result *v1alpha1.MeshWorkload, err error) {
	result = &v1alpha1.MeshWorkload{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("meshworkloads").
		Name(meshWorkload.Name).
		SubResource("status").
		Body(meshWorkload).
		Do().
		Into(result)
	return
}

// Delete takes name of the meshWorkload and deletes it. Returns an error if one occurs.
func (c *meshWorkloads) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("meshworkloads").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *meshWorkloads) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("meshworkloads").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched meshWorkload.
func (c *meshWorkloads) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MeshWorkload, err error) {
	result = &v1alpha1.MeshWorkload{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("meshworkloads").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
