// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/supergloo/api/v1/ingress.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//MeshIngress represents a managed ingress (edge router) which can proxy connections
//for services in Mesh managed by SuperGloo. SuperGloo will perform additional configuration,
//if necessary, to enable proxying services which are using mTLS for communication.
type MeshIngress struct {
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by supergloo during validation
	Status core.Status `protobuf:"bytes,100,opt,name=status,proto3" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,101,opt,name=metadata,proto3" json:"metadata"`
	// type of Mesh ingress represented by this resource
	//
	// Types that are valid to be assigned to MeshIngressType:
	//	*MeshIngress_Gloo
	MeshIngressType isMeshIngress_MeshIngressType `protobuf_oneof:"mesh_ingress_type"`
	// reference to the Mesh(s) that this ingress is acting upon
	// enable the ingress to route to services within these mTLS-enabled meshes
	Meshes               []*core.ResourceRef `protobuf:"bytes,3,rep,name=meshes,proto3" json:"meshes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MeshIngress) Reset()         { *m = MeshIngress{} }
func (m *MeshIngress) String() string { return proto.CompactTextString(m) }
func (*MeshIngress) ProtoMessage()    {}
func (*MeshIngress) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d220723bdc29937, []int{0}
}
func (m *MeshIngress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshIngress.Unmarshal(m, b)
}
func (m *MeshIngress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshIngress.Marshal(b, m, deterministic)
}
func (m *MeshIngress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshIngress.Merge(m, src)
}
func (m *MeshIngress) XXX_Size() int {
	return xxx_messageInfo_MeshIngress.Size(m)
}
func (m *MeshIngress) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshIngress.DiscardUnknown(m)
}

var xxx_messageInfo_MeshIngress proto.InternalMessageInfo

type isMeshIngress_MeshIngressType interface {
	isMeshIngress_MeshIngressType()
	Equal(interface{}) bool
}

type MeshIngress_Gloo struct {
	Gloo *GlooMeshIngress `protobuf:"bytes,1,opt,name=gloo,proto3,oneof"`
}

func (*MeshIngress_Gloo) isMeshIngress_MeshIngressType() {}

func (m *MeshIngress) GetMeshIngressType() isMeshIngress_MeshIngressType {
	if m != nil {
		return m.MeshIngressType
	}
	return nil
}

func (m *MeshIngress) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *MeshIngress) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *MeshIngress) GetGloo() *GlooMeshIngress {
	if x, ok := m.GetMeshIngressType().(*MeshIngress_Gloo); ok {
		return x.Gloo
	}
	return nil
}

func (m *MeshIngress) GetMeshes() []*core.ResourceRef {
	if m != nil {
		return m.Meshes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MeshIngress) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MeshIngress_OneofMarshaler, _MeshIngress_OneofUnmarshaler, _MeshIngress_OneofSizer, []interface{}{
		(*MeshIngress_Gloo)(nil),
	}
}

func _MeshIngress_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MeshIngress)
	// mesh_ingress_type
	switch x := m.MeshIngressType.(type) {
	case *MeshIngress_Gloo:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gloo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MeshIngress.MeshIngressType has unexpected type %T", x)
	}
	return nil
}

func _MeshIngress_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MeshIngress)
	switch tag {
	case 1: // mesh_ingress_type.gloo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GlooMeshIngress)
		err := b.DecodeMessage(msg)
		m.MeshIngressType = &MeshIngress_Gloo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MeshIngress_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MeshIngress)
	// mesh_ingress_type
	switch x := m.MeshIngressType.(type) {
	case *MeshIngress_Gloo:
		s := proto.Size(x.Gloo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Mesh ingress object for gloo
type GlooMeshIngress struct {
	Install              *GlooInstall       `protobuf:"bytes,1,opt,name=install,proto3" json:"install,omitempty"`
	Config               *MeshIngressConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GlooMeshIngress) Reset()         { *m = GlooMeshIngress{} }
func (m *GlooMeshIngress) String() string { return proto.CompactTextString(m) }
func (*GlooMeshIngress) ProtoMessage()    {}
func (*GlooMeshIngress) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d220723bdc29937, []int{1}
}
func (m *GlooMeshIngress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlooMeshIngress.Unmarshal(m, b)
}
func (m *GlooMeshIngress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlooMeshIngress.Marshal(b, m, deterministic)
}
func (m *GlooMeshIngress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlooMeshIngress.Merge(m, src)
}
func (m *GlooMeshIngress) XXX_Size() int {
	return xxx_messageInfo_GlooMeshIngress.Size(m)
}
func (m *GlooMeshIngress) XXX_DiscardUnknown() {
	xxx_messageInfo_GlooMeshIngress.DiscardUnknown(m)
}

var xxx_messageInfo_GlooMeshIngress proto.InternalMessageInfo

func (m *GlooMeshIngress) GetInstall() *GlooInstall {
	if m != nil {
		return m.Install
	}
	return nil
}

func (m *GlooMeshIngress) GetConfig() *MeshIngressConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type GlooInstall struct {
	// Generic installation options
	Options              *InstallOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GlooInstall) Reset()         { *m = GlooInstall{} }
func (m *GlooInstall) String() string { return proto.CompactTextString(m) }
func (*GlooInstall) ProtoMessage()    {}
func (*GlooInstall) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d220723bdc29937, []int{2}
}
func (m *GlooInstall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlooInstall.Unmarshal(m, b)
}
func (m *GlooInstall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlooInstall.Marshal(b, m, deterministic)
}
func (m *GlooInstall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlooInstall.Merge(m, src)
}
func (m *GlooInstall) XXX_Size() int {
	return xxx_messageInfo_GlooInstall.Size(m)
}
func (m *GlooInstall) XXX_DiscardUnknown() {
	xxx_messageInfo_GlooInstall.DiscardUnknown(m)
}

var xxx_messageInfo_GlooInstall proto.InternalMessageInfo

func (m *GlooInstall) GetOptions() *InstallOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type MeshIngressConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshIngressConfig) Reset()         { *m = MeshIngressConfig{} }
func (m *MeshIngressConfig) String() string { return proto.CompactTextString(m) }
func (*MeshIngressConfig) ProtoMessage()    {}
func (*MeshIngressConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d220723bdc29937, []int{3}
}
func (m *MeshIngressConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshIngressConfig.Unmarshal(m, b)
}
func (m *MeshIngressConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshIngressConfig.Marshal(b, m, deterministic)
}
func (m *MeshIngressConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshIngressConfig.Merge(m, src)
}
func (m *MeshIngressConfig) XXX_Size() int {
	return xxx_messageInfo_MeshIngressConfig.Size(m)
}
func (m *MeshIngressConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshIngressConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MeshIngressConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MeshIngress)(nil), "supergloo.solo.io.MeshIngress")
	proto.RegisterType((*GlooMeshIngress)(nil), "supergloo.solo.io.GlooMeshIngress")
	proto.RegisterType((*GlooInstall)(nil), "supergloo.solo.io.GlooInstall")
	proto.RegisterType((*MeshIngressConfig)(nil), "supergloo.solo.io.MeshIngressConfig")
}

func init() {
	proto.RegisterFile("github.com/solo-io/supergloo/api/v1/ingress.proto", fileDescriptor_5d220723bdc29937)
}

var fileDescriptor_5d220723bdc29937 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x9b, 0xd4, 0x4a, 0xd1, 0x5a, 0xa8, 0xf2, 0xb6, 0x42, 0x6e, 0x90, 0xda, 0x62, 0x21,
	0xd1, 0x03, 0x5d, 0x2b, 0xe5, 0x12, 0x15, 0x4e, 0xe6, 0x50, 0x8a, 0x54, 0x21, 0x2d, 0x37, 0x2e,
	0x95, 0xeb, 0x8c, 0x37, 0xab, 0xda, 0x1e, 0xcb, 0xbb, 0x46, 0xe2, 0xda, 0x1b, 0x6f, 0xc2, 0x8d,
	0xd7, 0xe0, 0x29, 0x7a, 0xe0, 0x0d, 0xca, 0x13, 0xa0, 0x5d, 0xaf, 0xab, 0x94, 0x04, 0x14, 0x4e,
	0x89, 0x67, 0xfe, 0xef, 0x9f, 0xdf, 0xe3, 0x21, 0x13, 0x21, 0xf5, 0xbc, 0xbd, 0x62, 0x19, 0x96,
	0xb1, 0xc2, 0x02, 0x8f, 0x25, 0xc6, 0xaa, 0xad, 0xa1, 0x11, 0x05, 0x62, 0x9c, 0xd6, 0x32, 0xfe,
	0x3c, 0x89, 0x65, 0x25, 0x1a, 0x50, 0x8a, 0xd5, 0x0d, 0x6a, 0xa4, 0xc1, 0x7d, 0x9f, 0x19, 0x82,
	0x49, 0x1c, 0xef, 0x0a, 0x14, 0x68, 0xbb, 0xb1, 0xf9, 0xd7, 0x09, 0xc7, 0x2b, 0xbd, 0xcd, 0xef,
	0xb5, 0xd4, 0xbd, 0x75, 0x09, 0x3a, 0x9d, 0xa5, 0x3a, 0x75, 0x48, 0xbc, 0x06, 0xa2, 0x74, 0xaa,
	0x5b, 0x17, 0x66, 0xfc, 0x72, 0x0d, 0xa0, 0x81, 0xfc, 0x3f, 0x12, 0xf5, 0xcf, 0x0e, 0x61, 0xeb,
	0x2c, 0xa8, 0x04, 0x35, 0xef, 0xf4, 0xd1, 0xf7, 0x21, 0xf1, 0x2f, 0x40, 0xcd, 0xcf, 0xbb, 0x9d,
	0xd1, 0x33, 0x32, 0xea, 0x02, 0x87, 0xb3, 0xc3, 0xc1, 0x91, 0x7f, 0xb2, 0xcb, 0x32, 0x6c, 0xa0,
	0xdf, 0x1c, 0xfb, 0x68, 0x7b, 0xc9, 0xde, 0x8f, 0xdb, 0x83, 0x8d, 0x5f, 0xb7, 0x07, 0x81, 0x06,
	0xa5, 0x67, 0x32, 0xcf, 0x4f, 0x23, 0x29, 0x2a, 0x6c, 0x20, 0xe2, 0x0e, 0xa7, 0x53, 0xf2, 0xa8,
	0x5f, 0x56, 0x08, 0xd6, 0xea, 0xc9, 0x43, 0xab, 0x0b, 0xd7, 0x4d, 0x3c, 0x63, 0xc6, 0xef, 0xd5,
	0x74, 0x4a, 0x3c, 0x13, 0x36, 0x1c, 0x58, 0x2a, 0x62, 0x4b, 0xdf, 0x8f, 0x9d, 0x15, 0x88, 0x0b,
	0xa1, 0xdf, 0x6d, 0x70, 0x4b, 0xd0, 0x09, 0x19, 0x99, 0x57, 0x03, 0x15, 0x6e, 0x1e, 0x6e, 0x1e,
	0xf9, 0x27, 0x7b, 0x0f, 0x27, 0x72, 0x50, 0xd8, 0x36, 0x19, 0x70, 0xc8, 0xb9, 0x13, 0x9e, 0x3e,
	0xbd, 0xb9, 0xf3, 0x3c, 0x32, 0x2c, 0xe5, 0xcd, 0x9d, 0xb7, 0x4d, 0x1f, 0x9b, 0xaa, 0x3b, 0x1f,
	0x50, 0xc9, 0x0e, 0x09, 0x4c, 0xe1, 0xd2, 0x55, 0x2e, 0xf5, 0x97, 0x1a, 0xa2, 0xaf, 0x03, 0xb2,
	0xfd, 0x47, 0x00, 0x3a, 0x25, 0x5b, 0xb2, 0x52, 0x3a, 0x2d, 0x0a, 0x97, 0x7a, 0xff, 0x2f, 0xa9,
	0xcf, 0x3b, 0x15, 0xef, 0xe5, 0xf4, 0x0d, 0x19, 0x65, 0x58, 0xe5, 0x52, 0x84, 0x43, 0x0b, 0x3e,
	0x5f, 0x01, 0x2e, 0x4c, 0x7a, 0x6b, 0xb5, 0xdc, 0x31, 0xd1, 0x7b, 0xe2, 0x2f, 0xb8, 0xd2, 0xd7,
	0x64, 0x0b, 0x6b, 0x2d, 0xb1, 0x52, 0x2e, 0xc6, 0xb3, 0x15, 0x6e, 0x4e, 0xfc, 0xa1, 0x13, 0xf2,
	0x9e, 0x88, 0x76, 0x48, 0xb0, 0x34, 0x28, 0x39, 0xfe, 0xf6, 0x73, 0x7f, 0xf0, 0xe9, 0xc5, 0x3f,
	0x8f, 0xaa, 0xbe, 0x16, 0xee, 0xb0, 0xae, 0x46, 0xf6, 0xa8, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x33, 0x92, 0xa0, 0xa7, 0x03, 0x00, 0x00,
}

func (this *MeshIngress) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshIngress)
	if !ok {
		that2, ok := that.(MeshIngress)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if that1.MeshIngressType == nil {
		if this.MeshIngressType != nil {
			return false
		}
	} else if this.MeshIngressType == nil {
		return false
	} else if !this.MeshIngressType.Equal(that1.MeshIngressType) {
		return false
	}
	if len(this.Meshes) != len(that1.Meshes) {
		return false
	}
	for i := range this.Meshes {
		if !this.Meshes[i].Equal(that1.Meshes[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshIngress_Gloo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshIngress_Gloo)
	if !ok {
		that2, ok := that.(MeshIngress_Gloo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Gloo.Equal(that1.Gloo) {
		return false
	}
	return true
}
func (this *GlooMeshIngress) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlooMeshIngress)
	if !ok {
		that2, ok := that.(GlooMeshIngress)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Install.Equal(that1.Install) {
		return false
	}
	if !this.Config.Equal(that1.Config) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *GlooInstall) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlooInstall)
	if !ok {
		that2, ok := that.(GlooInstall)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Options.Equal(that1.Options) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshIngressConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshIngressConfig)
	if !ok {
		that2, ok := that.(MeshIngressConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
