// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/solo-io/go-utils/hashutils"
	"go.uber.org/zap"
)

type NetworkBridgeSnapshot struct {
	MeshBridges MeshBridgeList
}

func (s NetworkBridgeSnapshot) Clone() NetworkBridgeSnapshot {
	return NetworkBridgeSnapshot{
		MeshBridges: s.MeshBridges.Clone(),
	}
}

func (s NetworkBridgeSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashMeshBridges(),
	)
}

func (s NetworkBridgeSnapshot) hashMeshBridges() uint64 {
	return hashutils.HashAll(s.MeshBridges.AsInterfaces()...)
}

func (s NetworkBridgeSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("meshBridges", s.hashMeshBridges()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}

type NetworkBridgeSnapshotStringer struct {
	Version     uint64
	MeshBridges []string
}

func (ss NetworkBridgeSnapshotStringer) String() string {
	s := fmt.Sprintf("NetworkBridgeSnapshot %v\n", ss.Version)

	s += fmt.Sprintf("  MeshBridges %v\n", len(ss.MeshBridges))
	for _, name := range ss.MeshBridges {
		s += fmt.Sprintf("    %v\n", name)
	}

	return s
}

func (s NetworkBridgeSnapshot) Stringer() NetworkBridgeSnapshotStringer {
	return NetworkBridgeSnapshotStringer{
		Version:     s.Hash(),
		MeshBridges: s.MeshBridges.NamespacesDotNames(),
	}
}
