// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/solo-io/gloo-mesh/api/certificates/pod_bounce_directive.proto

package v1alpha2

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	_ "github.com/solo-io/skv2/pkg/api/core.skv2.solo.io/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//When certificates are issued, pods may need to be bounced (restarted) to ensure they pick up the
//new certificates. If so, the certificate Issuer will create a PodBounceDirective containing the namespaces and labels
//of the pods that need to be bounced in order to pick up the new certs.
type PodBounceDirectiveSpec struct {
	// A list of k8s pods to bounce (delete and cause a restart)
	// when the certificate is issued.
	// This will include the control plane pods as well as any pods
	// which share a data plane with the target mesh.
	PodsToBounce         []*PodBounceDirectiveSpec_PodSelector `protobuf:"bytes,6,rep,name=pods_to_bounce,json=podsToBounce,proto3" json:"pods_to_bounce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *PodBounceDirectiveSpec) Reset()         { *m = PodBounceDirectiveSpec{} }
func (m *PodBounceDirectiveSpec) String() string { return proto.CompactTextString(m) }
func (*PodBounceDirectiveSpec) ProtoMessage()    {}
func (*PodBounceDirectiveSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f91a49be4602a86, []int{0}
}

func (m *PodBounceDirectiveSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodBounceDirectiveSpec.Unmarshal(m, b)
}
func (m *PodBounceDirectiveSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodBounceDirectiveSpec.Marshal(b, m, deterministic)
}
func (m *PodBounceDirectiveSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodBounceDirectiveSpec.Merge(m, src)
}
func (m *PodBounceDirectiveSpec) XXX_Size() int {
	return xxx_messageInfo_PodBounceDirectiveSpec.Size(m)
}
func (m *PodBounceDirectiveSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PodBounceDirectiveSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PodBounceDirectiveSpec proto.InternalMessageInfo

func (m *PodBounceDirectiveSpec) GetPodsToBounce() []*PodBounceDirectiveSpec_PodSelector {
	if m != nil {
		return m.PodsToBounce
	}
	return nil
}

// Pods that will be restarted.
type PodBounceDirectiveSpec_PodSelector struct {
	// The namespace in which the pods live.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Any labels shared by the pods.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Wait for this number of replacement pods to reach be fully Ready before
	// deleting the next set of selected pods.
	// This is used to ensure the control plane pods are allowed to restart
	// before sidecars and gateways are restarted.
	WaitForReplicas      uint32   `protobuf:"varint,3,opt,name=wait_for_replicas,json=waitForReplicas,proto3" json:"wait_for_replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodBounceDirectiveSpec_PodSelector) Reset()         { *m = PodBounceDirectiveSpec_PodSelector{} }
func (m *PodBounceDirectiveSpec_PodSelector) String() string { return proto.CompactTextString(m) }
func (*PodBounceDirectiveSpec_PodSelector) ProtoMessage()    {}
func (*PodBounceDirectiveSpec_PodSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f91a49be4602a86, []int{0, 0}
}

func (m *PodBounceDirectiveSpec_PodSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodBounceDirectiveSpec_PodSelector.Unmarshal(m, b)
}
func (m *PodBounceDirectiveSpec_PodSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodBounceDirectiveSpec_PodSelector.Marshal(b, m, deterministic)
}
func (m *PodBounceDirectiveSpec_PodSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodBounceDirectiveSpec_PodSelector.Merge(m, src)
}
func (m *PodBounceDirectiveSpec_PodSelector) XXX_Size() int {
	return xxx_messageInfo_PodBounceDirectiveSpec_PodSelector.Size(m)
}
func (m *PodBounceDirectiveSpec_PodSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_PodBounceDirectiveSpec_PodSelector.DiscardUnknown(m)
}

var xxx_messageInfo_PodBounceDirectiveSpec_PodSelector proto.InternalMessageInfo

func (m *PodBounceDirectiveSpec_PodSelector) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodBounceDirectiveSpec_PodSelector) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PodBounceDirectiveSpec_PodSelector) GetWaitForReplicas() uint32 {
	if m != nil {
		return m.WaitForReplicas
	}
	return 0
}

//
//PodBounceDirectiveStatus reports the status for stateful pod bounces (when bouncing pods requires waiting for readiness)
type PodBounceDirectiveStatus struct {
	// A list of k8s pods to bounce (delete and cause a restart)
	// when the certificate is issued.
	// This will include the control plane pods as well as any pods
	// which share a data plane with the target mesh.
	PodsBounced          []*PodBounceDirectiveStatus_BouncedPodSet `protobuf:"bytes,4,rep,name=pods_bounced,json=podsBounced,proto3" json:"pods_bounced,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *PodBounceDirectiveStatus) Reset()         { *m = PodBounceDirectiveStatus{} }
func (m *PodBounceDirectiveStatus) String() string { return proto.CompactTextString(m) }
func (*PodBounceDirectiveStatus) ProtoMessage()    {}
func (*PodBounceDirectiveStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f91a49be4602a86, []int{1}
}

func (m *PodBounceDirectiveStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodBounceDirectiveStatus.Unmarshal(m, b)
}
func (m *PodBounceDirectiveStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodBounceDirectiveStatus.Marshal(b, m, deterministic)
}
func (m *PodBounceDirectiveStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodBounceDirectiveStatus.Merge(m, src)
}
func (m *PodBounceDirectiveStatus) XXX_Size() int {
	return xxx_messageInfo_PodBounceDirectiveStatus.Size(m)
}
func (m *PodBounceDirectiveStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PodBounceDirectiveStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PodBounceDirectiveStatus proto.InternalMessageInfo

func (m *PodBounceDirectiveStatus) GetPodsBounced() []*PodBounceDirectiveStatus_BouncedPodSet {
	if m != nil {
		return m.PodsBounced
	}
	return nil
}

// A set of Pods that were restarted.
type PodBounceDirectiveStatus_BouncedPodSet struct {
	// The names of the pods that were bounced for the corresponding selector.
	BouncedPods          []string `protobuf:"bytes,1,rep,name=bounced_pods,json=bouncedPods,proto3" json:"bounced_pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodBounceDirectiveStatus_BouncedPodSet) Reset() {
	*m = PodBounceDirectiveStatus_BouncedPodSet{}
}
func (m *PodBounceDirectiveStatus_BouncedPodSet) String() string { return proto.CompactTextString(m) }
func (*PodBounceDirectiveStatus_BouncedPodSet) ProtoMessage()    {}
func (*PodBounceDirectiveStatus_BouncedPodSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f91a49be4602a86, []int{1, 0}
}

func (m *PodBounceDirectiveStatus_BouncedPodSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet.Unmarshal(m, b)
}
func (m *PodBounceDirectiveStatus_BouncedPodSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet.Marshal(b, m, deterministic)
}
func (m *PodBounceDirectiveStatus_BouncedPodSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet.Merge(m, src)
}
func (m *PodBounceDirectiveStatus_BouncedPodSet) XXX_Size() int {
	return xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet.Size(m)
}
func (m *PodBounceDirectiveStatus_BouncedPodSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet.DiscardUnknown(m)
}

var xxx_messageInfo_PodBounceDirectiveStatus_BouncedPodSet proto.InternalMessageInfo

func (m *PodBounceDirectiveStatus_BouncedPodSet) GetBouncedPods() []string {
	if m != nil {
		return m.BouncedPods
	}
	return nil
}

func init() {
	proto.RegisterType((*PodBounceDirectiveSpec)(nil), "certificates.mesh.gloo.solo.io.PodBounceDirectiveSpec")
	proto.RegisterType((*PodBounceDirectiveSpec_PodSelector)(nil), "certificates.mesh.gloo.solo.io.PodBounceDirectiveSpec.PodSelector")
	proto.RegisterMapType((map[string]string)(nil), "certificates.mesh.gloo.solo.io.PodBounceDirectiveSpec.PodSelector.LabelsEntry")
	proto.RegisterType((*PodBounceDirectiveStatus)(nil), "certificates.mesh.gloo.solo.io.PodBounceDirectiveStatus")
	proto.RegisterType((*PodBounceDirectiveStatus_BouncedPodSet)(nil), "certificates.mesh.gloo.solo.io.PodBounceDirectiveStatus.BouncedPodSet")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo-mesh/api/certificates/pod_bounce_directive.proto", fileDescriptor_6f91a49be4602a86)
}

var fileDescriptor_6f91a49be4602a86 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x76, 0x54, 0xaa, 0xb3, 0xf1, 0xc3, 0x42, 0x28, 0x8a, 0xd0, 0x28, 0x3b, 0x55,
	0x48, 0xb3, 0xb5, 0x72, 0x01, 0x8e, 0x15, 0x4c, 0x1c, 0x26, 0x84, 0x32, 0x4e, 0x5c, 0x22, 0x27,
	0x79, 0x4d, 0xad, 0x26, 0x7d, 0x96, 0xed, 0x84, 0xed, 0x4f, 0xe3, 0xc6, 0x3f, 0xc5, 0x85, 0x0b,
	0xc8, 0x8e, 0x81, 0xc2, 0xaa, 0x1d, 0xe0, 0x14, 0xfb, 0xfb, 0xbe, 0xf9, 0xbc, 0xf7, 0x4d, 0x6c,
	0xf2, 0xb6, 0x96, 0x76, 0xdd, 0x15, 0xac, 0xc4, 0x96, 0x1b, 0x6c, 0xf0, 0x54, 0x22, 0xaf, 0x1b,
	0xc4, 0xd3, 0x16, 0xcc, 0x9a, 0x0b, 0x25, 0x79, 0x09, 0xda, 0xca, 0x95, 0x2c, 0x85, 0x05, 0xc3,
	0x15, 0x56, 0x79, 0x81, 0xdd, 0xb6, 0x84, 0xbc, 0x92, 0x1a, 0x4a, 0x2b, 0x7b, 0x60, 0x4a, 0xa3,
	0x45, 0x7a, 0xbc, 0x6b, 0x64, 0xee, 0x75, 0xe6, 0x40, 0xcc, 0x51, 0x99, 0xc4, 0x94, 0xed, 0xe9,
	0x64, 0x36, 0xfd, 0x62, 0x68, 0x82, 0x1a, 0x78, 0x7f, 0xe6, 0x9f, 0x03, 0x2f, 0x7d, 0x52, 0x23,
	0xd6, 0x0d, 0x70, 0xbf, 0x2b, 0xba, 0x15, 0xb7, 0xb2, 0x05, 0x63, 0x45, 0xab, 0x82, 0xe1, 0xf8,
	0x6f, 0x43, 0xd5, 0x69, 0x61, 0x25, 0x6e, 0x43, 0x9d, 0xc2, 0x95, 0xf5, 0x2b, 0x0e, 0x57, 0x76,
	0xd0, 0x4e, 0xbe, 0x8f, 0xc8, 0xa3, 0xf7, 0x58, 0x2d, 0x7d, 0x84, 0xd7, 0x3f, 0x13, 0x5c, 0x2a,
	0x28, 0xe9, 0x9a, 0xdc, 0x55, 0x58, 0x99, 0xdc, 0x62, 0x48, 0x98, 0x4c, 0x66, 0xe3, 0x79, 0xbc,
	0x58, 0xb2, 0xdb, 0x83, 0xb1, 0xfd, 0x3c, 0x27, 0x5f, 0x42, 0x03, 0xa5, 0x45, 0x9d, 0x1d, 0x3a,
	0xf2, 0x07, 0x1c, 0x6c, 0xe9, 0xb7, 0x88, 0xc4, 0x3b, 0x55, 0xfa, 0x98, 0x4c, 0xb7, 0xa2, 0x05,
	0xa3, 0x44, 0x09, 0x49, 0x34, 0x8b, 0xe6, 0xd3, 0xec, 0xb7, 0x40, 0x57, 0x64, 0xd2, 0x88, 0x02,
	0x1a, 0x93, 0x8c, 0xfc, 0x3c, 0xef, 0xfe, 0x7f, 0x1e, 0x76, 0xe1, 0x81, 0x6f, 0xb6, 0x56, 0x5f,
	0x67, 0x81, 0x4e, 0x9f, 0x91, 0x07, 0x9f, 0x84, 0xb4, 0xf9, 0x0a, 0x75, 0xae, 0x41, 0x35, 0xb2,
	0x14, 0x26, 0x19, 0xcf, 0xa2, 0xf9, 0x51, 0x76, 0xcf, 0x15, 0xce, 0x51, 0x67, 0x41, 0x4e, 0x5f,
	0x92, 0x78, 0x07, 0x41, 0xef, 0x93, 0xf1, 0x06, 0xae, 0xc3, 0xe8, 0x6e, 0x49, 0x1f, 0x92, 0x3b,
	0xbd, 0x68, 0x3a, 0x48, 0x46, 0x5e, 0x1b, 0x36, 0xaf, 0x46, 0x2f, 0xa2, 0x93, 0xcf, 0x11, 0x49,
	0xf6, 0x4c, 0x68, 0x85, 0xed, 0x0c, 0x95, 0xc4, 0x7f, 0xa9, 0xf0, 0x03, 0xaa, 0xe4, 0xc0, 0x27,
	0x3e, 0xff, 0x87, 0xc4, 0x9e, 0xc7, 0x06, 0xb5, 0xf2, 0xd1, 0x6d, 0x16, 0x3b, 0x76, 0x90, 0xd2,
	0x05, 0x39, 0xfa, 0xa3, 0x4a, 0x9f, 0x92, 0xc3, 0xd0, 0x36, 0x77, 0xbe, 0x24, 0x9a, 0x8d, 0xe7,
	0xd3, 0x2c, 0x2e, 0x7e, 0x99, 0xcc, 0x32, 0xfb, 0xf2, 0xf5, 0x20, 0xfa, 0x78, 0x71, 0xeb, 0x95,
	0x51, 0x9b, 0xfa, 0xc6, 0xb5, 0xb9, 0x39, 0x32, 0xef, 0xcf, 0x44, 0xa3, 0xd6, 0x62, 0x51, 0x4c,
	0xfc, 0xc1, 0x7c, 0xfe, 0x23, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x52, 0x20, 0x3c, 0x89, 0x03, 0x00,
	0x00,
}
